apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # o que vou escalar
    name: products #nome do depoyment
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 2 # com base no request