apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-products-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      serviceAccountName: sa-products-svc
      containers:
        - name: products
          image: fabricio211/product-service:4.2
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-server-credentials
            - name: SPRING_CONFIG_LOCATION
              value: file:/etc/config/application.yml
          envFrom:
            - secretRef:
                name: mysql-server-credentials
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 700Mi
              cpu: "300m"
            requests:
              memory: 700Mi
              cpu: "300m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 40
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /etc/config
              name: config-products
      volumes:
        - name: config-products
          configMap:
            name: config-product
            items:
              - key: application.yml
                path: application.yml
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: products