apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: fabricio211/product:1.60.0
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/etc/config/application.yml
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 800Mi
              cpu: "350m"
            requests:
              memory: 800Mi
              cpu: "350m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 40
            timeoutSeconds: 8
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 8
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /etc/config
              name: config-products
      volumes:
        - name: config-products
          configMap:
            name: config-product
            items:
              - key: application.yml
                path: application.yml
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: products