apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1000Mi
            cpu: "300m"
          requests:
            memory: 1000Mi
            cpu: "300m"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 40
          timeoutSeconds: 2
          failureThreshold: 30
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1                