apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: test
  labels:
    name: myapp
spec:
  containers:
  - name: my-app-container
    image: busybox
    resources:
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
