apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmysql
  labels:
    type: localmysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce # so mais ser escrito e ligo por um nó
  persistentVolumeReclaimPolicy: Retain #vai reter esse volume DElete iria escluir e o Recycle, ele faz amount e mount quando não esta em uso ou em uso
  hostPath:
    path: "/volumes/mysql"