apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          volumeMounts:
            - mountPath: /data/db
              name: mysql-data
          args:
            - "--ignore-db-dir=lost+found"
          envFrom:
            - secretRef:
                name: mysql-server-credentials
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 350Mi
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: spvmysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306