apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spvmysql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi # posso usar até 10GB do meu persistent volume que vamos vincular
